### ISSUE TITLE
how to calculate metrics in object detection

### ISSUE THREAD

**Issue by xiyuxx** [ENSTA-U2IS/infraParis#7]
Dear authors,
     I want to know how do you calculate the metrics in object detection( the table 6 in paper). This is important for the comparing performances of different modals faithful. (And maybe you would like to offer me the calculation code). Thanks!

**Comment by giannifranchi** [comment]
We used the code of meta https://github.com/facebookresearch/maskrcnn-benchmark for the object detection. We did not intend to share this code because this is directly the code of meta.  For the calculation we use the classical metrics as usual.  I think you can find them on torchmetrics.
Best regards,

**Comment by xiyuxx** [comment]
Thanks for your answer!!
